# -*- coding: utf-8 -*-
"""Jogo da velha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-tVY5N6it8Dk2aGXPHOno1fYsXodCrC
"""

peca=int(input("Quer com X [0] ou O [1]?"))
opcao=int(input("Quer começar jogando [0] ou não [1]?"))

tabuleiro=[1,2,3,
           4,5,6,
           7,8,9]

class Jogador:
    def __init__(self):
        print("Vez do jogador")
    def jogar(self):
        print(tabuleiro[0:3])
        print(tabuleiro[3:6])
        print(tabuleiro[6:9])
        pos=int(input("quer jogar em qual posição (1 a 9, do canto superior esquerdo ao inferior direito"))
        if peca==0:
         tabuleiro[pos-1]="X"
        else:
         tabuleiro[pos-1]="●"
class Computador:
    def __init__(self):
        print("Vez do computador")
    def jogar(self):
        pos_disponiveis=[]
        for t in tabuleiro:
         if t in range (0,10):
          pos_disponiveis.append(t)

        if peca==0:
          if len(pos_disponiveis)>0:
           tabuleiro[min(pos_disponiveis)-1]="●"
        else:
          if len(pos_disponiveis)>0:
           tabuleiro[min(pos_disponiveis)-1]="X"

jogador=Jogador()
computador=Computador()
if opcao==0:
    while True:
     lista_fim=[]
     class Verificador:
          def __init__(self):
              print("Verificando a continuidade do jogo...")
          def verificar(self):
             if tabuleiro[0]==tabuleiro[1] and tabuleiro[0]==tabuleiro[2] and tabuleiro[1]==tabuleiro[2]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[3]==tabuleiro[4] and tabuleiro[4]==tabuleiro[5] and tabuleiro[3]==tabuleiro[5]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[6]==tabuleiro[7] and tabuleiro[6]==tabuleiro[8] and tabuleiro[8]==tabuleiro[7]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[0]==tabuleiro[4] and tabuleiro[0]==tabuleiro[8] and tabuleiro[4]==tabuleiro[8]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[2]==tabuleiro[4] and tabuleiro[4]==tabuleiro[6] and tabuleiro[2]==tabuleiro[6]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[0]==tabuleiro[3] and tabuleiro[3]==tabuleiro[6] and tabuleiro[0]==tabuleiro[6]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[1]==tabuleiro[4] and tabuleiro[1]==tabuleiro[7] and tabuleiro[4]==tabuleiro[7]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[2]==tabuleiro[5] and tabuleiro[2]==tabuleiro[8] and tabuleiro[5]==tabuleiro[8]:
              print("Fim de jogo")
              lista_fim.append("Fim")
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     verificador=Verificador()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     jogador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     computador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     jogador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     computador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     jogador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     computador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     jogador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     computador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     jogador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
else:
   while True:
     lista_fim=[]
     class Verificador:
          def __init__(self):
              print("Verificando a continuidade do jogo...")
          def verificar(self):
             if tabuleiro[0]==tabuleiro[1] and tabuleiro[0]==tabuleiro[2] and tabuleiro[1]==tabuleiro[2]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[3]==tabuleiro[4] and tabuleiro[4]==tabuleiro[5] and tabuleiro[3]==tabuleiro[5]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[6]==tabuleiro[7] and tabuleiro[6]==tabuleiro[8] and tabuleiro[8]==tabuleiro[7]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[0]==tabuleiro[4] and tabuleiro[0]==tabuleiro[8] and tabuleiro[4]==tabuleiro[8]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[2]==tabuleiro[4] and tabuleiro[4]==tabuleiro[6] and tabuleiro[2]==tabuleiro[6]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[0]==tabuleiro[3] and tabuleiro[3]==tabuleiro[6] and tabuleiro[0]==tabuleiro[6]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[1]==tabuleiro[4] and tabuleiro[1]==tabuleiro[7] and tabuleiro[4]==tabuleiro[7]:
              print("Fim de jogo")
              lista_fim.append("Fim")
             elif tabuleiro[2]==tabuleiro[5] and tabuleiro[2]==tabuleiro[8] and tabuleiro[5]==tabuleiro[8]:
              print("Fim de jogo")
              lista_fim.append("Fim")
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     verificador=Verificador()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     computador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     jogador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     computador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     jogador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     computador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     jogador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     computador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break
     jogador.jogar()
     verificador.verificar()
     if len(lista_fim)>0:
         print("Fim de jogo")
         break