# -*- coding: utf-8 -*-
"""Organização de arquivos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PVPezqk2AYLDHqTXqvI9cxhZ6Eu4A_ES
"""

import os
arquivos = os.listdir('/home/juan/Downloads')

os.chdir('/home/juan/Downloads')

os.mkdir('Pasta de CSV')
os.mkdir('Pasta de IPYNB')
os.mkdir('Pasta de PDF')
os.mkdir('Pasta de TXT')
os.mkdir('Pasta de JPG')
os.mkdir('Pasta de ZIP')

for a in arquivos:
    if 'txt' in a:
        os.rename(a,'Pasta de TXT/{}'.format(a))
    elif 'csv' in a:
        os.rename(a,'Pasta de CSV/{}'.format(a))
    elif 'pdf' in a:
        os.rename(a,'Pasta de PDF/{}'.format(a))
    elif 'zip' in a:
        os.rename(a,'Pasta de ZIP/{}'.format(a))
    elif 'JPG' in a:
        os.rename(a,'Pasta de JPG/{}'.format(a))
    elif 'ipynb' in a:
        os.rename(a,'Pasta de IPYNB/{}'.format(a))