# -*- coding: utf-8 -*-
"""Simulador de caos na academia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZsOgKVLg2e7De8x2DIcd3Rw3jK34puU
"""

import random
#pesos é o número de pesos no lugar
class PessoaOrganizada:
        def __init__(self):
                self.pesos=10
        def usar_e_guardar_peso(self):
                self.pesos-=0
class PessoaDesorganizada:
        def __init__(self):
                self.pesos = 10
        def usar_e_guardar_peso(self):
                self.pesos -= random.randint(0,1)
po=PessoaOrganizada()
pd=PessoaDesorganizada()
alunos=[1,2,3,4,5,6,7,8,9,10] #aluno 10 é desorganizado

# Uso 1
for a in alunos:
        usuário_peso=random.randint(0,10)
        if usuário_peso==10:
                pd.usar_e_guardar_peso()
        else:
                po.usar_e_guardar_peso()

# Uso 2

for a in alunos:
        usuário_peso=random.randint(0,10)
        if usuário_peso==10:
                pd.usar_e_guardar_peso()
        else:
                po.usar_e_guardar_peso()
# Uso 3

for a in alunos:
        usuário_peso=random.randint(0,10)
        if usuário_peso==10:
                pd.usar_e_guardar_peso()
        else:
                po.usar_e_guardar_peso()
# Uso 4
for a in alunos:
        usuário_peso=random.randint(0,10)
        if usuário_peso==10:
                pd.usar_e_guardar_peso()
        else:
                po.usar_e_guardar_peso()
# Uso 5
for a in alunos:
        usuário_peso=random.randint(0,10)
        if usuário_peso==10:
                pd.usar_e_guardar_peso()
        else:
                po.usar_e_guardar_peso()
# Uso 6
for a in alunos:
        usuário_peso=random.randint(0,10)
        if usuário_peso==10:
                pd.usar_e_guardar_peso()
        else:
                po.usar_e_guardar_peso()
# Uso 7
for a in alunos:
        usuário_peso=random.randint(0,10)
        if usuário_peso==10:
                pd.usar_e_guardar_peso()
        else:
                po.usar_e_guardar_peso()
# Uso 8
for a in alunos:
        usuário_peso=random.randint(0,10)
        if usuário_peso==10:
                pd.usar_e_guardar_peso()
        else:
                po.usar_e_guardar_peso()
# Uso 9
for a in alunos:
        usuário_peso=random.randint(0,10)
        if usuário_peso==10:
                pd.usar_e_guardar_peso()
        else:
                po.usar_e_guardar_peso()
# Uso 10
for a in alunos:
        usuário_peso=random.randint(0,10)
        if usuário_peso==10:
                pd.usar_e_guardar_peso()
        else:
                po.usar_e_guardar_peso()

print(pd.pesos)